/**
 * @typedef {Object} Node
 * @property {string} id
 * @property {string} geometry
 * @property {string} osmId
 * @property {number} changeset
 * @property {number} version
 * @property {string} timestamp
 * @property {string} tags
 * @property {number} lat
 * @property {number} lon
 */

/**
 * @typedef {Object} Edge
 * @property {string} id
 * @property {string} len
 * @property {string} v
 * @property {string} u
 * @property {string} geometry
 * @property {string} osm_type
 * @property {string} tags
 * @property {number} version
 * @property {string} timestamp
 * @property {string} osmId
 * @property {string} width
 * @property {string} tunnel
 * @property {string} surface
 * @property {string} segregated
 * @property {string} service
 * @property {string} psv
 * @property {string} overtaking
 * @property {string} oneway
 * @property {string} name
 * @property {string} motor_vehicle
 * @property {string} motorcar
 * @property {string} maxspeed
 * @property {string} lit
 * @property {number} lanes
 * @property {string} int_ref
 * @property {string} highway
 * @property {string} footway
 * @property {string} foot
 * @property {string} cycleway
 * @property {string} bridge
 * @property {string} bicycle
 * @property {string} area
 * @property {string} access
 */

/**
 * @typedef {Object} PointOfInterest
 * @property {string} id
 * @property {string} addr_full
 * @property {string} addr_city
 * @property {string} addr_country
 * @property {string} addr_housenumber
 * @property {string} addr_housename
 * @property {string} addr_postcode
 * @property {string} addr_street
 * @property {string} addr_place
 * @property {string} email
 * @property {string} name
 * @property {string} opening_hours
 * @property {string} operator
 * @property {string} phone
 * @property {string} private_or_public
 * @property {string} url
 * @property {string} website
 * @property {string} building
 * @property {string} amenity
 * @property {string} building_levels
 * @property {string} landuse
 * @property {string} office
 * @property {string} shop
 * @property {string} source
 * @property {string} start_date
 * @property {string} wikipedia
 * @property {string} osmId
 * @property {string} timestamp
 * @property {number} version
 * @property {string} geometry
 * @property {string} tags
 * @property {string} osm_type
 * @property {string} internet_access
 * @property {number} changeset
 * @property {string} craft
 * @property {number} lat
 * @property {number} lon
 * @property {string} atm
 * @property {string} bicycle_parking
 * @property {string} cafe
 * @property {string} childcare
 * @property {string} parking
 * @property {string} social_facility
 * @property {string} books
 * @property {string} butcher
 * @property {string} clothes
 * @property {string} erotic
 * @property {string} religion
 * @property {string} second_hand
 * @property {string} information
 * @property {string} tourism
 * @property {string} bicycle
 * @property {string} coffee
 * @property {string} collector
 * @property {string} dry_cleaning
 * @property {string} fuel
 * @property {string} furniture
 * @property {string} massage
 * @property {string} motorcycle
 * @property {string} music
 * @property {string} organic
 * @property {string} outdoor
 * @property {string} pet
 * @property {string} trade
 * @property {string} wine
 * @property {string} attraction
 * @property {string} museum
 * @property {string} bar
 * @property {string} car_wash
 * @property {string} drinking_water
 * @property {string} leisure
 * @property {string} outdoor_seating
 * @property {string} playground
 * @property {string} caravan
 * @property {string} golf
 * @property {string} swimming_pool
 * @property {string} water
 * @property {string} wholesale
 * @property {string} viewpoint
 * @property {string} zoo
 * @property {string} gambling
 * @property {string} theatre
 * @property {string} fitness_station
 * @property {string} poi_type
 */

/**
 * @typedef {Object} Building
 * @property {string} id
 * @property {string} phone
 * @property {string} addr_city
 * @property {string} addr_country
 * @property {string} addr_full
 * @property {string} addr_housenumber
 * @property {string} addr_housename
 * @property {string} addr_postcode
 * @property {string} addr_street
 * @property {string} addr_place
 * @property {string} email
 * @property {string} name
 * @property {string} opening_hours
 * @property {string} operator
 * @property {string} private_or_public
 * @property {string} url
 * @property {string} website
 * @property {string} building
 * @property {string} amenity
 * @property {string} building_levels
 * @property {string} building_material
 * @property {string} building_min_level
 * @property {string} height
 * @property {string} landuse
 * @property {string} office
 * @property {string} shop
 * @property {string} source
 * @property {string} start_date
 * @property {string} wikipedia
 * @property {string} osmId
 * @property {string} timestamp
 * @property {number} version
 * @property {string} geometry
 * @property {string} tags
 * @property {string} osm_type
 * @property {string} internet_access
 * @property {string} changeset
 * @property {string} craft
 */